SELECT * FROM cachorro.cachorros;

INSERT INTO CACHORROS 
VALUES 
(1,"TOY", "GOLDEN","KASSIANE");

ALTER TABLE CACHORROS
ADD idade int ;

ALTER TABLE CACHORROS
DROP idade ;

UPDATE CACHORROS
SET NOME = "PRINCESA"
WHERE ID = 1 ;

ALTER TABLE NOMEDATABLE ADD FOREIGN KEY (`CHAVEESTRANGE`) REFERENCES `TABELADEREFERENCIA` (`CHAVEPRIMARIA`);