
CREATE DATABASE TUTORIAL;

DROP DATABASE TUTORIAL;

USE TUTORIAL;
CREATE TABLE CIDADE(
ID INT PRIMARY KEY,
NOME VARCHAR(100),
BAIRRO VARCHAR(100),
RUAS VARCHAR(200),
AVENIDAS VARCHAR(200)
);

DROP TABLE CIDADE;


INSERT INTO CIDADE 
VALUES 
( 2,"QUIXADA","COMBATE","JOSE","DOM"),
( 3,"QUIXADA","COMBATE","JOSE","DOM"),
( 4,"QUIXADA","COMBATE","JOSE","DOM"),
( 5,"QUIXADA","COMBATE","JOSE","DOM"),
( 6,"QUIXADA","COMBATE","JOSE","DOM");

