# CRIAÇÃO DE TABELAS 
# LER TABELAS 
# ALTERAR TABELAS - UPDATE
# DELETAR DROP COLUNAS TABELAS DATABASES
# SET O QUE A GENTE ALTERA WHERE LOCALIZA 
# LIKE NO WHERE
# CSV - IMPORTAÇÕES
# TIPOS DE DADOS
# TRANSAÇÕES - COMMIT E ROLLBACK 
# INSERT 
# SGBD
# ALTERAR COLUNA PARA CHAVE ESTRANGEIRA
# ADD

# CRUD
# C - CREATE - INSERT
# R - READ - SELECT
# U - UPDATE - UPDATE
# D - DELETE - DELETE



