SELECT EMAIL as email_usuario FROM USUARIOS;

SELECT email, id FROM USUARIOS;

SELECT * FROM USUARIOS WHERE ID = 11 OR ID = 33;
SELECT * FROM USUARIOS WHERE ID = 11 AND ID = 33;

SELECT * FROM USUARIOS WHERE NOT ID = 13;


